CREATE TABLE user_accounts (
  user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  username VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  password_hash VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  role VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  must_change_password TINYINT(1) NOT NULL DEFAULT 1,
  failed_login_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  failed_window_started_at DATETIME(3) NULL,
  locked_until DATETIME(3) NULL,
  password_changed_at DATETIME(3) NOT NULL,
  last_login_at DATETIME(3) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_user_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_user_accounts_role CHECK (role IN ('admin', 'advisor')),
  CONSTRAINT chk_user_accounts_status CHECK (status IN ('enabled', 'disabled')),
  CONSTRAINT chk_user_accounts_must_change_password CHECK (must_change_password IN (0, 1)),
  CONSTRAINT chk_user_accounts_version CHECK (version > 0),
  UNIQUE KEY uq_user_accounts_username (username),
  INDEX idx_user_accounts_status_role (status, role, user_id),
  INDEX idx_user_accounts_locked (locked_until, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
