CREATE TABLE score_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id BIGINT UNSIGNED NOT NULL,
  exam_date DATE NOT NULL,
  subject VARCHAR(64) NOT NULL,
  record_type VARCHAR(8) NOT NULL,
  exam_name VARCHAR(160) NOT NULL,
  score DECIMAL(10,2) NOT NULL,
  full_score DECIMAL(10,2) NOT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_score_records_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_score_records_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_score_records_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT chk_score_records_subject CHECK (CHAR_LENGTH(TRIM(subject)) BETWEEN 1 AND 64),
  CONSTRAINT chk_score_records_type CHECK (record_type IN ('quiz', 'exam')),
  CONSTRAINT chk_score_records_name CHECK (CHAR_LENGTH(TRIM(exam_name)) BETWEEN 1 AND 160),
  CONSTRAINT chk_score_records_score CHECK (score >= 0),
  CONSTRAINT chk_score_records_full_score CHECK (full_score > 0),
  CONSTRAINT chk_score_records_score_range CHECK (score <= full_score),
  CONSTRAINT chk_score_records_version CHECK (version > 0),
  INDEX idx_score_records_student_date (student_id, exam_date, id),
  INDEX idx_score_records_student_subject_date (student_id, subject, exam_date, id),
  INDEX idx_score_records_subject_type_date (subject, record_type, exam_date, id),
  INDEX idx_score_records_updated (updated_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;
